### ISSUE TITLE
PowerBi template expects costings in USD

### ISSUE THREAD

**Issue by JonRippon** [Azure/azure-docs-powershell-samples#326] opened 2021-03-01 10:09 UTC
I have been trying to work with the Azure Migrate Assessment comparison template, when I upload my exports I see errors as the template query's are  set to expect costings in USD. I have all of them but still receive one last error for the CentralSummaryTable error (Below)

 "'Total monthly cost estimate USD' in table 'CentralSummaryTable' cannot be found or may not be used in this expression."

The query has been changed to GBP but I still see the same error ?

```
let
   
   Source = try Summary otherwise Table.FromRecords(
    {  
      [Assessment name = "", Total monthly cost estimate GBP = "", Compute monthly cost GBP = "", Storage monthly cost GBP = ""]
    }
   ),
  
    #"Source1" = #"Source",
    #"Appended Query" = Table.Combine({Source1, #"Summary (2)", #"Summary (3)", #"Summary (4)", #"Summary (5)", #"Summary (6)", #"Summary (7)", #"Summary (8)", #"Summary (9)", #"Summary (10)", #"Summary (11)", #"Summary (12)"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Appended Query",{{"Total monthly cost estimate GBP", type number}, {"Compute monthly cost GBP", type number}, {"Storage monthly cost GBP", type number}})
in
    #"Changed Type"
```

Many thanks 
Jon

**Comment by mikefrobbins** [comment] 2021-03-02 18:58
@JonRippon Can you provide a link or the name of the sample script in this repo that you're using?

**Comment by JonRippon** [comment] 2021-03-12 15:26
@mikefrobbins I`m using the Azure Migrate Assessment Comparison PowerBI Template within the Azure/azure-docs-powershell-samples/tree/master/azure-migrate/assessment-utility repo

**Comment by mikefrobbins** [comment] 2021-03-19 17:23
@JonRippon, I've reached out to the service team who owns that particular service and template. Based on the response I received, @shikhersaluja should be following up.

**Comment by shikhersaluja** [comment] 2021-03-25 19:10
@JonRippon and @mikefrobbins I would like to clarify that this is not a part of an officially shipped product and hence customizations aren't supported. It is just a template, that users may choose to customize given their knowledge of PowerBI scripting. This template was designed to be used for USD only. 

@JonRippon, can you check if it is working, when your assessments are in USD? You need to import all the CSV files in one go ie one after the other, without refreshing the dashboard for data to show up accurately (as indicated in the documentation).
As you make customizations, you would have to modify all the dependencies in the PowerBI script are related to currencies.

Additionally, in order to make customizations you must make the changes before loading data into the template (this includes making changes to all the dependencies), and then as indicated above import all CSVs in one go.

**Comment by mikefrobbins** [comment] 2021-04-08 13:45
@JonRippon We're going to proceed with closing this issue based on @shikhersaluja's response since there have been no follow-up responses in the past 2 weeks. If you need further assistance, let us know.

**Closed by mikefrobbins** 2021-04-08 13:45 UTC
